In [19]:
from itertools import combinations_with_replacement
import numpy as np
class PolynomialF:
    def __init__(self,degree=2):
        self.degree = degree

    def transform(self,x):
        x= np.array(x) 
         # this line to make sure that the x is array  to apply multiplication in row and coloumns (combinations )
        n_sampels,n_features=x.shape
        polyfeatures=np.ones((n_sampels,1))
        # this is the bias term  ,  this line allows me to put it in matrix not in vector
        # 5 houses every house has 3 feature
        # x is the  data set with ex 2features
        for d in range(1,self.degree+1):
            for i in combinations_with_replacement(range(n_features),d):
                            # for i in combinations_with_replacement([0,1],2):
                            # print(i)
                            # the out put will be (0,0)(0,1)(1,1)
                 new_features = np.prod(x[:,i],axis=1,keepdims=True)
                 polyfeatures=np.c_[polyfeatures,new_features]
        return polyfeatures  

x=np.arange(6).reshape(3,2)
poly=PolynomialF(degree=2)
new_x=poly.transform(x)
print(x)
print(new_x)





[[0 1]
 [2 3]
 [4 5]]
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [8]:
#x= [a,b]  
# if he gives me one feature then my function should create x power 2
# so if there is a and b so i should have   a^2  & b^2   with the original  a ,b 
# and ab :)


In [ ]:
import numpy as np
l=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
l=np.array(l)
np.prod(l[:,(0,0)],axis=1,keepdims=True)
# this line to keep result of multiplication in 2d shape



In [ ]:
# الكام سطر دول بيختصرو المدعكة الي فوق بس هم حرفيا يجيبه بدايات جلطة
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree =3,include_bias=True)
# will include bias term
new_x =poly.fit_transform(x)


